### PR TITLE
#34: Still not working reliably... (closes #34)

### LINKED ISSUE #34: Still not working reliably...
## description
1. #30 should warn only in dev
2. should handle the case where there are no `children`

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
{optional: describe a possible fix for this bug, if not obvious}

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #34

### tests performed
- with previous code test what happens if FlexView has no children -> error
- with new code test what happens if FlexView has no children -> no error
- in dev -> I see the warning
- in prod -> I didn't test..

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/FlexView.js [hunk 1]
```diff
@@ -7,8 +7,10 @@ import omit from 'lodash/omit';
 import some from 'lodash/some';
 import { t, props } from 'tcomb-react';
 
+const IS_DEV = process.env.NODE_ENV !== 'production';
```
Comment (giogonzo) [inline src/FlexView.js]: I think we can be smarter in the future, but for now I'd leave the check inline (I mean the entire `process.env.NODE_ENV`) so that our builds can strip the useless code below. With a variable like this, it doesn't currently work in our average project build

Comment (FrancescoCioria) [inline src/FlexView.js]: 👍
