### PR TITLE
#30: IE11: `hAlignContent='center'` fails if children use `margin: auto` (closes #30)

### LINKED ISSUE #30: IE11: `hAlignContent='center'` fails if children use `margin: auto`
## description
In IE11 `hAlignContent='center'` fails to center horizontally a child that uses `margin: auto`.

## how to reproduce
```jsx
<FlexView hAlignContent='center' width={200} height={200} style={{ background: 'red' }}>
  <div style={{ marginLeft: 'auto', marginRight: 'auto', width: 100, background: 'blue' }} />
</FlexView>
```

In IE11 the blue div is not centered:

image

## specs
if:
- in dev
- FlexView has marginLeft/Right "auto"
- parent is a FlexView that centers horizontally

then:
- log a warning to remove useless `margin: auto`

## misc
{optional: other useful info}

### PR DESCRIPTION
**Pull request by FrancescoCioria**
Closes #30

### tests performed
image

image

> An example of partial test is a field displaying 4 possible values. If 3 values are tested, with screenshots, and 1 is not, then it should be mentioned here.}

### CODE REVIEW

File: src/FlexView.js [hunk 1]
```diff
@@ -86,6 +87,26 @@ export default class FlexView extends React.Component<void, IProps, void> {
...
+        const marginLeft = style.marginLeft || props.marginLeft;
+        const marginRight = style.marginRight || props.marginRight;
+        return marginLeft === 'auto' && marginRight === 'auto';
+      });
+
+      atLeastOnChildrenHasHMarginAuto && warn('In a row with hAlignContent="center" there should be no child with marginLeft and marginRight set to "auto"\nhttps://github.com/buildo/react-flexview/issues/30');
+    }
+
+    if (column && vAlignContent === 'center') {
+      const atLeastOnChildrenHasHMarginAuto = some([].concat(children), child => {
```
Comment (giogonzo) [inline src/FlexView.js]:
```diff
-atLeastOnChildrenHasHMarginAuto
+atLeastOnChildrenHasVMarginAuto
```
:nerd_face:
